Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2023
Var
// Seção de Declarações das variáveis 
n,cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite um valor interio de 1 a 10")
leia(n)
cont<-1
enquanto (cont<11) faca
escreval(n, " x", cont, " =", n*cont)
cont<-cont+1
fimenquanto

Fimalgoritmo